---
title: "BSSRC Poster"
output:
  pdf_document: default
  html_document: default
date: "2023-02-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r working chunk - copy this}
library(gstat)
library(raster)
library(sp)
library(sf)
library(tidyverse)
library(janitor)
library(cowplot)
library(tinytex)
library(rlang)
library(ragg)
GISPOINTS <- read_csv("C:/Users/gnyen/Desktop/GISPOINTS.txt")
HEMIMESS <- read_csv("C:/Users/gnyen/Desktop/HEMIMESS.csv") %>% clean_names()
SHPFILE1 <- sf::st_read("C:/Users/gnyen/Desktop/ceststands/estab_outline.shp") %>% mutate(stand_id = 1:n()) 
GISPOINTS <- GISPOINTS %>% clean_names()
Allpts <- HEMIMESS %>% left_join(GISPOINTS) #%>% clean_names()


#Adam changes
stand_9_shp <- SHPFILE1 %>% filter(stand_id == 9)   #1  #8  #9*
stand_4_plots <- Allpts %>% filter(stand_id == 4)   #3  #5  #4*


(layer9_stand_4 <- ggplot(stand_9_shp) +
  geom_sf(aes()) +
 # labs(title = "Geolocations In Stands")+
   # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = stand_4_plots, aes(x = x_lat, y = y_long, #alpha = percent_cnpy_open, 
                                      size = percent_cnpy_open, color = percent_cnpy_open)) +
    scale_size_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2)) +
    #scale_alpha_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2)) +
    scale_color_continuous(guide = "legend", limits=c(34, 48), breaks=seq(34, 48, by=2), type = "viridis") +
    theme_minimal(base_size = 8))

layer9_stand_4

# NEXT PLOT

stand_1_shp <- SHPFILE1 %>% filter(stand_id == 1)   #1  #8  #9*
stand_3_plots <- Allpts %>% filter(stand_id == 3)   #3  #5  #4*

(layer1_stand_3 <- ggplot(stand_1_shp) +
  geom_sf(aes()) +
  #labs(title = "Geolocations In Stands")+
   # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = stand_3_plots, aes(x = x_lat, y = y_long, #alpha = percent_cnpy_open, 
                                      size = percent_cnpy_open, color = percent_cnpy_open)) +
    scale_size_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2)) +
    #scale_alpha_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2)) +
    scale_color_continuous(guide = "legend", limits=c(34, 48), breaks=seq(34, 48, by=2), type = "viridis") +
    theme_minimal(base_size = 8))


layer1_stand_3


# NEXT PLOT

stand_8_shp <- SHPFILE1 %>% filter(stand_id == 8)   #1  #8  #9*
stand_5_plots <- Allpts %>% filter(stand_id == 5)   #3  #5  #4*

(layer8_stand_5 <- ggplot(stand_8_shp) +
  geom_sf(aes()) + 
  labs(title = "Geolocations In Stands", )+ 
    
   # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = stand_5_plots, aes(x = x_lat, y = y_long, #alpha = percent_cnpy_open, 
                                      size = percent_cnpy_open, color = percent_cnpy_open)) +
    scale_size_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2)) +
    #scale_alpha_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2)) +
    scale_color_continuous(guide = "legend", limits=c(34, 48), breaks=seq(34, 48, by=2), type = "viridis") +
    theme_minimal(base_size = 8))



```

```{r}
#Adam changes
#Below is the site that I used to combine colors
#https://community.rstudio.com/t/ggplot2-legend-not-combining-color-size-aes-for-the-same-variable/124606 
#stand_8_shp <- SHPFILE1 %>% filter(stand_id == 8)   #1  #8  #9*
#stand_5_plots <- Allpts %>% filter(stand_id == 5)   #3  #5  #4*


#layer8_stand_5 <- ggplot(stand_8_shp) +
#  geom_sf(aes()) +
#  labs(title = "Geolocations In Stands")+
   # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
# geom_point(data = stand_5_plots, aes(x = x_lat, y = y_long, #alpha = percent_cnpy_open, 
 #                                     size = percent_cnpy_open, color = percent_cnpy_open) #+
  # This one# scale_size_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2)) +
    #scale_alpha_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2)) +
   # scale_color_continuous(guide = "legend", limits=c(34, 48), breaks=seq(34, 48, by=2), type = "viridis") +
#    theme_minimal()) + ylab(NULL)





```

```{r}
#this chunk is for cowplot
library(rlang)

p1 <- layer8_stand_5 + ylab(NULL) + xlab(NULL)
p2 <- layer1_stand_3 + ylab(NULL) + xlab(NULL)
# p3 <- layer9_stand_4 + ylab(NULL)


#this makes them in a row
prow <- plot_grid(
  p1 + theme(legend.position="none", axis.text.x = element_text(angle = 90)) +ggtitle("Canopy Openness Within Stands")+ theme(plot.title = element_text(size=20)),
  p2 + theme(legend.position="none", axis.text.x = element_text(angle = 90)),
 # p3 + theme(legend.position="none", axis.text.x = element_text(angle = 90)),
  align = 'vh',
  labels = c(),
  hjust = -1,
  nrow = 1
)
prow

#this spits out a legend that it pulls from one of the plots

legend_b <- get_legend(
  p1 + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

# add the legend underneath the row we made earlier. Give it 10%
# of the height of one plot (via rel_heights).
plot_grid(prow, legend_b, ncol = 1, rel_heights = c(.1, .05)) #Mess with the last number
```
```{r Lets get some Phosphorus Rolling!}

library(gstat)
library(raster)
library(sp)
library(sf)
library(tidyverse)
library(ggplot2)
library(janitor)
library(cowplot)
library(tinytex)
library(rlang)
library(ragg)
benju_phos <- read_csv("C:/Users/gnyen/Desktop/benju_phos.csv")
GISPOINTS <- read_csv("C:/Users/gnyen/Desktop/GISPOINTS.txt")
HEMIMESS <- read_csv("C:/Users/gnyen/Desktop/HEMIMESS.csv") %>% clean_names()
SHPFILE1 <- sf::st_read("C:/Users/gnyen/Desktop/ceststands/estab_outline.shp") %>% mutate(stand_id = 1:n()) 
GISPOINTS <- GISPOINTS %>% clean_names()
Allpts <- HEMIMESS %>% left_join(GISPOINTS) 
#as_tibble(p_ten_in)
#as_tibble(benju_phos)
benju_phos %>%rename(stand_id = stand) 
names(benju_phos)[1] <- "stand_id"
names(benju_phos)[2] <- "plot_id"
p_ten_in <- filter(benju_phos, depth == "0-10")
colnames(benju_phos)
plot_phos <-left_join(benju_phos, Allpts, by = "plot_id")
PIP <- left_join(p_ten_in, Allpts, by = "plot_id" ) 
#PIP = Phosphorus In Plots
#view(PIP)

standP <- ggplot(p_ten_in, aes(x= stand, y= P, size= P, alpha= P)) + geom_point(color= "green2")



stand_8_shp <- SHPFILE1 %>% filter(stand_id == 8)   #1  #8  #9*
stand_5_phos <- PIP %>% filter(stand_id.x == 5)   #3  #5  #4*

(layer8_phos_5 <- ggplot(stand_8_shp) +
  geom_sf(aes()) + 
  labs(title = "", )+ 
    
### # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = stand_5_phos, shape= 17, aes(x = x_lat, y = y_long, 
                                     
                                      size = P, color = P)) +
   scale_size_continuous(limits=c(0, 12), breaks=seq(0, 12, by=2)) +
    #scale_alpha_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2)) +
    scale_color_continuous(guide = "legend", limits=c(0, 12), breaks=seq(0, 12, by=2), type = "viridis") +
    theme_minimal(base_size = 8))

#view(stand_3_phos) 
#view(p_ten_in)




stand_1_shp <- SHPFILE1 %>% filter(stand_id == 1)   #1  #8  #9*
stand_3_phos <- PIP %>% filter(stand_id.x == 3)   #3  #5  #4*

(layer1_phos_3 <- ggplot(stand_1_shp) +
  geom_sf(aes()) + 
  labs(title = "", )+ 
    
### # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = stand_3_phos, shape = 17, aes(x = x_lat, y = y_long, 
                                     
                              size= P,         color = P)) +
   scale_size_continuous(limits=c(0, 12), breaks=seq(0, 12, by=2)) +
   ## scale_alpha_continuous(limits=c(0, 11), breaks=seq(0, 11, by=2)) +
   scale_color_continuous(guide = "legend", limits=c(0, 12), breaks=seq(0, 12, by=2), type = "viridis") +
    theme_minimal(base_size = 8))

#summary(plot_phos %>% filter(stand_id.x == 3))
```

```{r Cowplot some phos bro!}


p3 <- layer8_phos_5
p4 <- layer1_phos_3

library(rlang)

p3 <- layer8_phos_5 + ylab(NULL) + xlab(NULL)
p4 <- layer1_phos_3 + ylab(NULL) + xlab(NULL)
# p3 <- layer9_stand_4 + ylab(NULL)


#this makes them in a row
prow <- plot_grid(
  p3 + theme(legend.position="none", axis.text.x = element_text(angle = 90)) +ggtitle(" Extractable P Concentrations (mg/kg) ")+ theme(plot.title = element_text(size=20)),
  p4 + theme(legend.position="none", axis.text.x = element_text(angle = 90)),
 # p3 + theme(legend.position="none", axis.text.x = element_text(angle = 90)),
  align = 'vh',
  labels = c(),
  hjust = -1,
  nrow = 1
)
prow

#this spits out a legend that it pulls from one of the plots

legend_b <- get_legend(
  p3 + 
    guides(color = guide_legend(nrow = 1)) +
    theme(legend.position = "bottom")
)

# add the legend underneath the row we made earlier. Give it 10%
# of the height of one plot (via rel_heights).
plot_grid(prow, legend_b, ncol = 1, rel_heights = c(.1, .05)) #Mess with the last numbe
```

