---
title: "CA Example"
output: html_document
date: "2023-02-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(broom)
library("ggplot2")
theme_set(theme_bw()) #this sets the map theme in ggplot to dark on light
library(sf)
library(forcats)
library(rnaturalearth)
library(rnaturalearthdata)
library(kknn)
library("ggspatial")
library(rgdal)
library(terra)
library(stars)
library(gstat)
library(automap)
library(abind)
```

```{r}
rainfall <- read.csv("C:/Users/gnyen/Downloads/data/_book/data/rainfall.csv")
```

```{r}
library(sf)

rainfall = st_as_sf(rainfall, coords = c("x_utm", "y_utm"), crs = 32636)
m = c("sep", "oct", "nov", "dec", "jan", "feb", "mar", "apr", "may")
rainfall$annual = apply(st_drop_geometry(rainfall[, m]), 1, sum)
```

```{r}
#Import Datasets
gis_points <- read_file("C:/Users/gnyen/Desktop/GISPOINTS.txt")
all_shps <- read_file("C:/Users/gnyen/Desktop/ceststands/estab_outline.shp")
hemi_data <- read_file("C:/Users/gnyen/Desktop/HEMIMESS.csv")

GISPOINTS %>% rename(x_utm = x_lat) %>% rename(y_utm = y_long)  

gis_hemi <- full_join(GISPOINTS, HEMIMESS, by = "plot_id")

```

```{r}

gis_hemi = st_as_sf(gis_hemi, coords = select(gis_hemi, x_utm, y_utm), crs= 32636)
gis_hemi %>% st_as_sf(c("x_utm", "y_utm"), crs = 100)

plot_light = gis_hemi$percent_cnpy_open
gis_hemi$ = apply(st_drop_geometry(gis_hemi[, plot_light]), 1)
```
```{r}
library(sf)
library(ggplot2)
library(apcf)

setwd("C:/Users/gnyen/Desktop/ceststands")
aoi <- st_read("estab_outline.shp")
plot(aoi$geometry)
st_geometry_type(aoi)
ggplot



aoi %>% fortify(geometry)


plot(aoi$geometry)

px <- Allpts$x_lat
py <- Allpts$y_long
pz <- Allpts$X..Cnpy.Open

full_join("px", "py")

data.frame(c(px, py, pz)) %>% matrix()

dat <- data.frame(c(px, py, pz))

tmp <- data.frame(x=gl(2,3),
  y=gl(3,1,6),
  z=c(1,2,3,3,3,2))

fig <- plot_ly(z = ~tmp)
fig <- fig %>% add_surface()

fig

volcano

dat

```

```{r}
# https://rspatial.org/analysis/4-interpolation.html
if (!require("rspat")) remotes::install_github('rspatial/rspat')


library(rspat)
d <- spat_data('precipitation')
head(d)

mnts <- toupper(month.abb)
d$prec <- rowSums(d[, mnts])
plot(sort(d$prec), ylab="Annual precipitation (mm)", las=1, xlab="Stations")

dsp <- vect(d, c("LONG", "LAT"), crs="+proj=longlat +datum=NAD83")
CA <- spat_data("counties")
# define groups for mapping
cuts <- c(0,200,300,500,1000,3000)
# set up a palette of interpolated colors
blues <- colorRampPalette(c('yellow', 'orange', 'blue', 'dark blue'))
plot(CA, col="light gray", lwd=4, border="dark gray")
plot(dsp, "prec", type="interval", col=blues(10), legend=TRUE, cex=2,
    breaks=cuts, add=TRUE, plg=list(x=-117.27, y=41.54))
lines(CA)

TA <- "+proj=aea +lat_1=34 +lat_2=40.5 +lat_0=0 +lon_0=-120 +x_0=0 +y_0=-4000000 +datum=WGS84 +units=m"
dta <- project(dsp, TA)
cata <- project(CA, TA)

RMSE <- function(observed, predicted) {
  sqrt(mean((predicted - observed)^2, na.rm=TRUE))
}

null <- RMSE(mean(dsp$prec), dsp$prec)
null
## [1] 435.3217

v <- voronoi(dta)
plot(v)
points(dta)

vca <- crop(v, cata)
plot(vca, "prec")

r <- rast(vca, res=10000)
vr <- rasterize(vca, r, "prec")
plot(vr)
```

