---
title: "GEOHEMI"
output: html_document
date: "2023-02-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(broom)
library("ggplot2")
theme_set(theme_bw()) #this sets the map theme in ggplot to dark on light
library(sf)
library(forcats)
library(rnaturalearth)
library(rnaturalearthdata)
library(kknn)
library("ggspatial")
library(rgdal)
library(terra)

```

## Stand ID is where the overlap betwen the two data sets lies.##

```{r}
HEMIMESS <- read_csv("C:/Users/gnyen/Desktop/HEMIMESS.csv")
colnames(LAT.LONGS)[4]  <- "Plot.ID"    # change column name for columns to match under Plot.ID

cleandf <-inner_join(HEMIMESS,LAT.LONGS, by=c("Plot.ID")) # Joined the two data sets matched between Plot.ID
print(cleandf)
```

```{r}
##This chunk is for pruning down the dataframe

df1 <- select(cleandf, StandID.x, Plot.ID, X, Y, X..Site.Open, LAI.4Ring) #Here I selected the useful data
print(df1)


```
```{r}
library(rgdal)
shape <- readOGR(dsn = ".", layer = "twingates.shp")
```

```{r} 
## another test chunk to fix the one above
library("sf")


aoi_boundary <- st_read(
  "C:/Users/gnyen/Desktop/SHPS/twingates.shp") #this one points to the file and reads it.

(sites <- data.frame(longitude = c(select(df1, 2)), latitude = c(select(df1, 3))))

ggplot(data = aoi_boundary, size = 3, color = black, fill = "cyan1") + # this is where you put the shapefile of the jones center/ stands #JC is where "world" was
    geom_sf() +
    geom_point(data = df1, aes(x = X, y = Y), size = 3, 
        shape = 23, fill = "darkred") +
       coord_sf(xlim = c(-84.40, -84.51), ylim = c(31.185, 31.24), expand = FALSE)
```
```{r} 
#this works to plot the plots!!!
library(sf)
library(ggplot2)
library(apcf)
setwd("C:/Users/gnyen/Desktop/ceststands")
aoi <- st_read("estab_outline.shp")
plot(aoi$geometry)
st_geometry_type(aoi)

GISPOINTS <- read_csv("C:/Users/gnyen/Desktop/GISPOINTS.txt")


```

```{r}
##This chunk is for pruning down the dataframe

new_pts <- select(GISPOINTS, StandID, PlotID, X_LAT, Y_LONG,) #Here I selected the useful data
print(new_pts)

```




```{r}

library("sf")
library(gstat)
g <- gstat(formula = Allpts$X..Cnpy.Open ~ 1, data = Allpts)
SHPFILE1 <- sf::st_read("C:/Users/gnyen/Desktop/ceststands/estab_outline.shp") #%>% mutate(stand_id = 1:n())  
ggplot(SHPFILE1) +
  geom_sf(aes()) +
 geom_point(data = Allpts, aes(x = X_LAT, y = Y_LONG), size = 5, 
        shape = 23, fill = pull(Allpts, X..Cnpy.Open))


      

```

```{r}

library("sf")



   # change column name for columns to match under Plot.ID
colnames(GISPOINTS)[3]  <- "Plot.ID"
Allpts <-inner_join(cleandf, GISPOINTS, by=c("Plot.ID")) # Joined the two data sets matched between Plot.ID
print(Allpts)




#setwd("C:/Users/gnyen/Desktop/ceststands")
#SHPFILE1 <- sf::st_read("C:/Users/gnyen/Desktop/ceststands/estab_outline.shp") %>% mutate(stand_id = 1:n()) 




layer1 <- ggplot(SHPFILE1) +
  geom_sf(aes()) +
  labs(title = "Geolocations In Stands")+
   # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = Allpts , aes(x = X_LAT, y = Y_LONG, alpha = X..Cnpy.Open, color= X..Cnpy.Open))

     

mid<- median(Allpts$X..Cnpy.Open)
layer1+scale_color_gradient2(midpoint=mid, low="cyan2", mid="blue",
                     high="red", space ="Lab" )
 filter(SHPFILE1, REGENYEAR == 1986) %>% plot(SHPFILE1$geometry)

stand_1_shp <- layer1 %>% filter(data$geometry == 1)
stand_1_plots <- Allpts %>% filter(StandID == 4)

(layer1_stand_3 <- ggplot(stand_1_shp) +
  geom_sf(aes()) +
  labs(title = "Geolocations In Stands")+
   # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = stand_1_plots, aes(x = X_LAT, y = Y_LONG, alpha = X..Cnpy.Open, color= X..Cnpy.Open)))

     

mid<- median(Allpts$X..Cnpy.Open)
(layer1_stand_3+scale_color_gradient2(midpoint=mid, low="cyan2", mid="blue",
                     high="red", space ="Lab" ))


#stand_id 2 and 5 are STANDID 1
#stand_id 3 and 4 and 6 are STANDID 2

stand_1_shp <- SHPFILE1 %>% filter %>% filter(stand_id == c(2, 4, 6))
                      
stand_1_plots <- Allpts %>% filter(StandID == 2)

(layer1_stand_3 <- ggplot(stand_1_shp) +
  geom_sf(aes()) +
  labs(title = "Geolocations In Stands")+
   # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = stand_1_plots, aes(x = X_LAT, y = Y_LONG, alpha = X..Cnpy.Open, color= X..Cnpy.Open)))

     

mid<- median(Allpts$X..Cnpy.Open)
(layer1_stand_3+scale_color_gradient2(midpoint=mid, low="cyan2", mid="blue",
                     high="red", space ="Lab" ))


```

```{r}

library("sf")



   # change column name for columns to match under Plot.ID
colnames(GISPOINTS)[3]  <- "Plot.ID"
Allpts <-inner_join(cleandf, GISPOINTS, by=c("Plot.ID")) # Joined the two data sets matched between Plot.ID
print(Allpts)




setwd("C:/Users/gnyen/Desktop/ceststands")
SHPFILE1 <- sf::st_read("C:/Users/gnyen/Desktop/ceststands/estab_outline.shp") %>% mutate(stand_id = 1:n()) 




layer1 <- ggplot(SHPFILE1) +
  geom_sf(aes()) +
  labs(title = "Geolocations In Stands")+
   # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = Allpts , aes(x = X_LAT, y = Y_LONG, alpha = X..Cnpy.Open, color= X..Cnpy.Open))

     

mid<- median(Allpts$X..Cnpy.Open)
layer1+scale_color_gradient2(midpoint=mid, low="cyan2", mid="blue",
                     high="red", space ="Lab" )
                     



  # Crop to Germany
    germ_rast <- 
      dialects_raster %>%
        st_intersection(germany)
    
    
      # Basic view of rasterized data
    ggplot() + 
      geom_raster(data=germ_rast, 
                  aes(x=lon, y=lat, 
                      fill=dialect)) 
    
  
```


```{r}
library(janitor)
HEMIMESS <- read_csv("C:/Users/gnyen/Desktop/HEMIMESS.csv") %>% clean_names()
GISPOINTS <- GISPOINTS %>% clean_names()
Allpts <- HEMIMESS %>% left_join(GISPOINTS) #%>% clean_names()

#Adam changes
stand_1_shp <- SHPFILE1 %>% filter(stand_id == 1)
stand_1_plots <- Allpts %>% filter(stand_id == 3)

(layer1_stand_3 <- ggplot(stand_1_shp) +
  geom_sf(aes()) +
  labs(title = "Geolocations In Stands")+
   # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = stand_1_plots, aes(x = x_lat, y = y_long, alpha = percent_cnpy_open, color= percent_cnpy_open)))

     

mid<- median(Allpts$percent_cnpy_open)
(layer1_stand_3+scale_color_gradient2(midpoint=mid, low="cyan2", mid="blue",
                     high="red", space ="Lab" ))



#new stuff here

#plot_buff <- SHPFILE1 %>% st_buffer(dist= 1000)

width_in_pixels = 500# 300 is better but slower 
  # dx is the width of a grid cell in meters
    (dx <- ceiling( (st_bbox(stand_1_shp)["xmax"] - 
                    st_bbox(stand_1_shp)["xmin"]) / width_in_pixels))
  # dy is the height of a grid cell in meters
  # because we use quadratic grid cells, dx == dy
  dy = dx
  # calculate the height in pixels of the resulting grid
  height_in_pixels <- floor( (st_bbox(stand_1_shp)["ymax"] - 
                              st_bbox(stand_1_shp)["ymin"]) / dy)
# Make the grid   
  grid <- st_make_grid(stand_1_shp, 
                       cellsize = dx,
                       n = c(width_in_pixels, height_in_pixels),
                       what = "centers")

test <- st_as_sf(stand_1_plots, coords = c("x_lat", "y_long"))

#plot_buff
  # Prepare data for interpolation
  # Create tibble of the German responses sf object
    cnpy_open_input <- test %>%
                    tibble(cnpy_open = .$percent_cnpy_open, 
                             lon = st_coordinates(.)[, 1], 
                             lat = st_coordinates(.)[, 2]) %>%
                      select(cnpy_open, lon, lat)
    
     #(   cnpy_open_input_GN <- test %>%
  #                 tibble(cnpy_open = .$X..Cnpy.Open, 
    #                       lon = st_coordinates(.)[, 1], 
     #                        lat = st_coordinates(.)[, 2]) %>%
      #                select(cnpy_open, lon, lat) 

    
knn = 100
    cnpy_open_output <- data.frame(cnpy_open = as.factor(NA), 
                              lon = st_coordinates(grid)[, 1], 
                              lat = st_coordinates(grid)[, 2])
    
cnpy_open_output_kknn <- kknn::kknn(cnpy_open ~ ., 
                               train = cnpy_open_input, 
                               test = cnpy_open_output, 
                               kernel = "gaussian",  
                               k = knn)  
            
 
 cnpy_open_output <-
        cnpy_open_output %>%
          mutate(cnpy_open = fitted(cnpy_open_output_kknn),
                 # only retain the probability of the interpolated variable,
                 prob = apply(cnpy_open_output_kknn$prob, 
                              1, 
                              function(x) max(x)))
                  
     # Transform interpolation tibble to sf
    dialects_raster <- st_as_sf(stand_1_plots, 
                                coords = c("X", "Y"),
                                crs = crs_etrs,
                                remove = F)
    
    
```

```{r working chunk - copy this}
library(gstat)
library(raster)
library(sp)
library(tidyverse)
library(janitor)
HEMIMESS <- read_csv("C:/Users/gnyen/Desktop/HEMIMESS.csv") %>% clean_names()
SHPFILE1 <- sf::st_read("C:/Users/gnyen/Desktop/ceststands/estab_outline.shp") %>% mutate(stand_id = 1:n()) 
GISPOINTS <- GISPOINTS %>% clean_names()
Allpts <- HEMIMESS %>% left_join(GISPOINTS) #%>% clean_names()


#Adam changes
stand_1_shp <- SHPFILE1 %>% filter(stand_id == 1)
stand_1_plots <- Allpts %>% filter(stand_id == 3)


(layer1_stand_3 <- ggplot(stand_1_shp) +
  geom_sf(aes()) +
  labs(title = "Geolocations In Stands")+
   # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = stand_1_plots, aes(x = x_lat, y = y_long, #alpha = percent_cnpy_open, 
                                      size = percent_cnpy_open, color = percent_cnpy_open)) +
    scale_size_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2)) +
    #scale_alpha_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2)) +
    scale_color_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2)) +
    theme_minimal())


mid<- median(stand_1_plots$X..Cnpy.Open)
layer1_stand_3+scale_color_gradient2(midpoint=mid, low="cyan2", mid="blue",
                     high="red", space ="Lab" )


```


```{r}
library(gstat)
library(raster)
library(sp)

library(janitor)
HEMIMESS <- read_csv("C:/Users/gnyen/Desktop/HEMIMESS.csv") %>% clean_names()
GISPOINTS <- GISPOINTS %>% clean_names()
Allpts <- HEMIMESS %>% left_join(GISPOINTS) #%>% clean_names()
mid<- median(Allpts$percent_cnpy_open)

#Adam changes
stand_1_shp <- Allpts %>% filter(stand_id == 1)
stand_1_plots <- Allpts %>% filter(stand_id == 3)

mid <- median(stand_1_plots$X..Cnpy.Open)

 l1 <- ((layer1_stand_3 <- ggplot(stand_1_shp) +
  geom_sf(aes()) +
  labs(title = "Geolocations In Stands")+
   # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = stand_1_plots, aes(x = x_lat, y = y_long, size = percent_cnpy_open)) ))

   
   mid<- median(Allpts$X..Cnpy.Open)
layer1+scale_color_gradient2(midpoint=mid, low="cyan2", mid="blue",
                     high="red", space ="Lab" )
      geom_point(colour = "orange", size = 4.5) 
   
 print(l1) 
    scale_size_continuous(limits=c(34, 48), breaks=seq(34, 48, by=2))) 
        


```
```{r}
library("sf")
library(gstat)
library(raster)
library(sp)
library(tidyverse)

library(janitor)
GISPOINTS <- read_csv("C:/Users/gnyen/Desktop/GISPOINTS.txt")
HEMIMESS <- read_csv("C:/Users/gnyen/Desktop/HEMIMESS.csv") %>% clean_names()
SHPFILE1 <- sf::st_read("C:/Users/gnyen/Desktop/ceststands/estab_outline.shp") %>% mutate(stand_id = 1:n()) 
GISPOINTS <- GISPOINTS %>% clean_names()
Allpts <- HEMIMESS %>% left_join(GISPOINTS) #%>% clean_names()
mid<- median(Allpts$percent_cnpy_open)

#Adam changes
stand_1_shp <- SHPFILE1 %>% filter(stand_id == 1)
stand_1_plots <- Allpts %>% filter(stand_id == 3)


   # change column name for columns to match under Plot.ID
colnames(GISPOINTS)[3]  <- "Plot.ID"
Allpts <-inner_join(cleandf, GISPOINTS, by=c("Plot.ID")) # Joined the two data sets matched between Plot.ID
print(Allpts)




#setwd("C:/Users/gnyen/Desktop/ceststands")




(layer1 <- ggplot(SHPFILE1) +
  geom_sf(aes()) +
  labs(title = "Geolocations In Stands")+
   # geom_sf_label(data = SHPFILE1, aes(label = A), size=3) +
 geom_point(data = Allpts , aes(x = X_LAT, y = Y_LONG, alpha = X..Cnpy.Open, color= X..Cnpy.Open)))

     

mid<- median(Allpts$X..Cnpy.Open)
layer1+scale_color_gradient2(midpoint=mid, low="cyan2", mid="blue",
                     high="red", space ="Lab" )

library(sf)
library(ggplot2)
library(apcf)
setwd("C:/Users/gnyen/Desktop/ceststands")
aoi <- st_read("estab_outline.shp")
plot(aoi$geometry)
st_geometry_type(aoi)

GISPOINTS <- read_csv("C:/Users/gnyen/Desktop/GISPOINTS.txt")


```

