---
title: "Spring'24 Code"
author: "GNyen"
date: "2024-02-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r "Chunk 1 Import data and library packages, set up cluster"}
library(tidyverse)
library(glmmADMB)
library(broom)
library(vegan)
library(parallel)
library(janitor)
detectCores() # counts how many cores the computer has # this is just good to know for the makeCluster() argument

metadata<- read.csv("C:/Users/gn238/Downloads/gn_metadata_wzeros.csv") #this is my meta data from the understory community change over time study

metadata$row <- as.factor(metadata$row) #CHANGE row to be a factor 
metadata$stand <- as.factor(metadata$stand) #CHANGE stand to be a factor
 


regendata <- read.csv("C:/Users/gn238/OneDrive - Mississippi State University/R - Copy/r_pull_from/regenplots.csv") #here is the meta data on the understory regen. This includes height of trees, metadata does not






clus <- parallel::makeCluster(15) # creates a cluster using 15 of 16 cores

clusterEvalQ(clus, library(vegan)) # allow vegan to use the cluster when running any function

```


```{r "set up regendata averaged by sampling plot"}

regendata <- regendata %>% 
    dplyr::select(-starts_with('X')) %>% #this removes the data columns that didn't contain any information
    clean_names() %>% #this uses janitor to make the names lowercase and better
       separate(col = plot_id,  into = c("stand", "transect", "position")) #this gives a new column for each by separating stand, transect, and position
regendata$standbyrow <- paste(regendata$stand, "_", regendata$row) #this created a new row in regendata for "stand_by_row" a mixture of how does row type and stand interact 


regendata$row <- as.factor(regendata$row) #CHANGE row to be a factor
regendata$stand <- as.factor(regendata$stand) #CHANGE stand to be a factor
```


```{r "add a seed trt column"}

seed1 <- regendata %>% filter(stand == 6) #this makes a small table of just stand 6 and all of its data
seed2 <- regendata %>% filter(stand == 7) #same for 7
seed3 <- regendata %>% filter(stand == 8) # same for 8
seed4 <- regendata %>% filter(stand == 9) 
trts5 <- bind_rows(seed1,seed2,seed3,seed4) #make a table with all of the seeded stands from the smaller tables above
trts6 <- trts5 %>% add_column(add_column = "S") #all of this created new column with "S" for seeded

unse1 <- regendata %>% filter(stand == 3) #this makes a small table of just stand 3 and all of its data from regendata
unse2 <- regendata %>% filter(stand == 4) #same for stand 4
unse3 <- regendata %>% filter(stand == 5) #same for stand 5 
unse4 <- regendata %>% filter(stand == 10)
trtu5 <- bind_rows(unse1,unse2,unse3,unse4)
trtu5 <- trtu5 %>% add_column(add_column = "U") #all of this created new column with "U" for unseeded

regendata <- bind_rows(trts6, trtu5) #this mashed the two tables together (U) and (S)
regendata <- rename(regendata, seed_trt = add_column) #this changed the name of the new column to "seed_trt" which now contains a S or a U.
regendata$seed_trt <- as.factor(regendata$seed_trt) #sets seed trt as a factor
 





```


```{r} 
regen_summary <- regendata %>% 
  group_by(seed_trt, stand, transect, position, row, quadrat) %>%  # organizes the table by these
  summarise(n_seedlings  = length(position[regen_count>=1]), #this does some math on n_seedlings
            mean_height = mean(height_cm)) #this creates a new df and makes it averaged by heights and counts per quadrat

regen_summary$standbyrow <- paste(regen_summary$stand, "_", regen_summary$row)
#this created a new row in regen_summary for "stand_by_row" a mixture of how does row type and stand interact 
 
```



```{r "lets get regendata averaged per row"}


STAND_ROW_SUMMARY   <- regen_summary %>% group_by(stand, row, seed_trt) %>% 
            summarise(n_seedlings_mean = mean(n_seedlings), #takes N_seedlings and makes a new collum of the mean of the seedlings per new grouping specified by the group_by function
            n_seedlings_sd = sd(n_seedlings),
            height_mean = mean(mean_height, na.rm = TRUE),
            height_sd = sd(mean_height, na.rm = TRUE)) 
#this is a summary table from regen_summary where each stand has a row type and a seed trt assigned to it. Average heights, and numbers of seedlings alongside SD's are listed in the table. Useful for testing trt effects based on row type
STAND_ROW_SUMMARY #print out the table


stand_transect_summary  <-regen_summary %>% group_by(stand, transect, row, seed_trt) %>%  #here I am sorting down to the transect to get finer data
            summarise(n_seedlings_mean = mean(n_seedlings), #makes a new variable off of the mean of n_seedlings based on the grouping above
            n_seedlings_sd = sd(n_seedlings), #makes new variable of sd of n_seedlings based off grouping above
            height_mean = mean(mean_height, na.rm = TRUE),  #same logic as above
            height_sd = sd(mean_height, na.rm = TRUE)) #same as above
stand_transect_summary #print out the table
 stand_transect_summary$standbyrow <- paste(stand_transect_summary$stand, "_", stand_transect_summary$row)
#this is a summary table from regen_summary where each stand is broken up by transect. Transects had an assigned row type and a seeding treatment. All values had Average heights, and numbers of seedlings alongside SD's are listed in the table.
 
 
 
```


```{r}
#This chunk is for stand/transect grouping. So replicates are transects within the stand. Remember that transects are nested within treatment and row type  <- i(jk)



m1 <- aov(n_seedlings_mean ~ seed_trt, data = stand_transect_summary) #anova testing if seed trt has an effect on seedlings
summary(m1) #seed treatment has a p value of 0.013  !!!!!!
#We have significant number of seedlings predicted by seed treatment
checkheight <- lm(n_seedlings_mean ~ seed_trt, data=stand_transect_summary) #anova testing if seed trt has an effect on seedlings
glance(checkheight) #same as m1 but in lm form !!!!!

m2 <- aov(n_seedlings_mean ~ row, data= stand_transect_summary) #anova testing if row type has an effect on seedlings
glance(m2) ## not significant
summary(m2)

m3 <- aov(height_mean ~ seed_trt, data = stand_transect_summary) #anova testing if seed_trt has an effect on seedlings
summary(m3) ## not significant

m4 <- aov(height_mean ~ row, data = stand_transect_summary ) #anova testing if row type has an effect on seedlings
summary(m4) ## not significant

m5 <- aov(n_seedlings_mean ~ stand, data = stand_transect_summary ) #anova testing if the stand has an effect on seedlings
summary(m5) # stand is extremely significant in determining mean number of seedlings or mean number of seedlings are greatly impacted by height !!! !!! !!! 


ggplot(stand_transect_summary, aes(
  x = factor(stand, levels = c(3, 4, 5, 10, 6, 7, 8, 9)), #breaks up the stands into levels of the factor (individual stands)
  y = n_seedlings_mean, 
  fill = row # makes it so there is a differential based on the row of the stands
)) +   geom_boxplot() + theme_minimal() #this is a ggplot using stand transects as the replicates with mean number of seedlings filled into the boxplot


```



```{r}
#This chunk is for stand/row groupings. So replicates are row types within the stand. Remember that stand is nested within treatment <- i(j)


m1 <- aov(n_seedlings_mean ~ seed_trt, data = STAND_ROW_SUMMARY)
summary(m1) #!!! !!! .0452 p value.
#We have significant number of seedlings predicted by seed treatment
checkheight <- lm(n_seedlings_mean ~ seed_trt, data=STAND_ROW_SUMMARY)
summary(checkheight) #same as m1 but as a linear model

m2 <- aov(n_seedlings ~ standbyrow, data= regen_summary)
glance(m2)
summary(m2)

m3 <- aov(n_seedlings_mean ~ row, data = STAND_ROW_SUMMARY)
summary(m3) #N seedlings not significantly affected by row type

m80 <- aov(n_seedlings_mean ~ stand, data = STAND_ROW_SUMMARY)
summary(m80) #N seedlings not significantly affected by row type


testing<- STAND_ROW_SUMMARY
testing[is.na(testing)] <- 0 #this created a new data frame where all NA values have been zeroed out


m4 <- aov(height_mean ~ row, data = testing )
summary(m4) #height is not significant by row

head(STAND_ROW_SUMMARY)
m5 <- aov(height_mean ~ row, data = STAND_ROW_SUMMARY)
summary(m5) #height is not significant by row

m5 <- aov(height_mean ~ stand, data = STAND_ROW_SUMMARY)
summary(m5) #height is not significant by row

m5 <- aov(height_mean ~ seed_trt, data = STAND_ROW_SUMMARY)
summary(m5) #height is not significant by row



### make plots to visualize the models ###
ggplot(data=testing, aes( x=row, y= height_mean)) + geom_boxplot() +
  theme_minimal()

ggplot(data=regen_summary, aes(x=stand, y=n_seedlings)) +
  geom_boxplot() +theme_minimal()

ggplot(data=regen_summary, aes(x=standbyrow, y=n_seedlings)) +
  geom_boxplot() +theme_minimal()

ggplot(STAND_ROW_SUMMARY, aes(
  x = factor(stand, levels = c(3, 4, 5, 10, 6, 7, 8, 9)),
  y = n_seedlings_mean,
  fill = row
)) +   geom_boxplot() + theme_minimal()


ggplot(data=STAND_ROW_SUMMARY, aes(x=seed_trt, y=height_mean), na.rm=T) +
  geom_boxplot() + theme_minimal()

### make plots to visualize the models ###
```

```{r}
#> AverageLiveBAperHa

trtz <- c("U","U","U","S","S","S","S","U") #make a treatment vector
stands<- c(3,4,5,6,7,8,9,10) #make a stand vector
AverageLiveBAperHA<- c(15.02291,8.62360,11.40782,13.34491,10.57843,14.65041,14.55944,12.90943) #make a average live BA Vector. This all came from output from another document. This is the summary that I am using to see if there was a difference in BA/ stand or treatment

badiff<- cbind.data.frame(trtz, stands, AverageLiveBAperHA) #creates the data.frame from the vectors above
badiff$trtz <- as.factor(badiff$trtz) #set trtz as a factor ~ factors have levels so you can use an anova
badiff$stands <- as.factor(badiff$stands) #sets the stands as a factor ~ factors have levels so you can use an anova


m007 <- aov(AverageLiveBAperHA ~ trtz, data= badiff) #anova testing if there was a diff of basal area based on the treatment
summary(m007) #nope, no diff based on treatment
m006 <- aov(AverageLiveBAperHA ~ stands, data= badiff) # anova testing if there was a diff of basal area based on the stands
summary(m006)  #nope, no diff based on thte tands
```


```{r}
#lets make a glmmADMB model after what Joshua J. Puhlick sent me


metadata<- read.csv("C:/Users/gn238/Downloads/gn_metadata_wzeros.csv", header=T, na.strings="")
#import the metadata, make all empty entries into NA's

metadata <- metadata %>% mutate(species_code = coalesce(species_code, species))
head(metadata, 20)
#replace all blank species with the unknown official names listed in the species_code column

data <-metadata %>% filter(!is.na(species_code))
#get rid of the entries without a species code after the coalesce.

data <- data %>% filter(!plot_id=="9-6-K")
#takes out a plot that didnt have data to it

varibs <- data %>% summarise(plot_id, n_seedlings, openness, lai_2000_lin, ppfd_total_under_per_day_m_jor_mol_m2day, gap_fraction, row, stand, transect) %>%
 distinct()
#create a variable data frame

varibs<- varibs  %>% replace_na(list(plot_id=0, n_seedlings=0, openness=0, lai_2000_lin = 0, ppfd_total_under_per_day_m_jor_mol_m2day = 0, gap_fraction= 0, row = "L", stand=0, standbyrow= 0))
#changes the NA values to be the resting values of zero or in the row it changes to a Leave row


dat1 <- data %>% dplyr::select(plot_id, species_code, dried_weight_g) %>%
  pivot_wider(names_from = species_code, values_from = dried_weight_g, values_fn = sum, values_fill = 0)
#this transforms the data frame into a wide format such that it can be used in NMDS


#add up spp weights to pool for each plot
dat1_long <- dat1 %>% 
  pivot_longer(!plot_id, names_to = "species", values_to = "biomass")

dat1_summary <- dat1_long %>% 
  group_by(plot_id) %>%
  summarise(biomass_sum = sum(biomass))
#add up spp weights to pool for each plot

 dat1_long1 <- dat1_long %>% 
       mutate(species = as.character(species))


dat1_long_noPIPA <- dat1_long1 %>% filter(species != "PIPA")

dat1_summary_noPIPA <- dat1_long_noPIPA %>% 
  group_by(plot_id) %>%
  summarise(biomass_sum = sum(biomass))

#this is a df with species weight on the inside and plot & species as headers
input_dat <- dat1 %>% column_to_rownames("plot_id")
#this is a df with species weight on the inside and plot & species as headers



  #plot side/axis 1 and 2 of 3D figure
  
  ### This is to add a seeding treatment to trts by way of using varibs in the chain ###
seeded6 <- varibs %>% filter(stand == 6)
seeded7 <- varibs %>% filter(stand == 7)
seeded8 <- varibs %>% filter(stand == 8)
seeded9 <- varibs %>% filter(stand == 9)
trtseed <- bind_rows(seeded6,seeded7,seeded8,seeded9)
trtseed <- trtseed %>% add_column(add_column = "S")
#~~~#~~~#~~~#~~~#~~~#~~~#~~~#
unseed3 <- varibs %>% filter(stand == 3)
unseed4 <- varibs %>% filter(stand == 4)
unseed5 <- varibs %>% filter(stand == 5)
unseed10 <- varibs %>% filter(stand == 10)
trtunseed <- bind_rows(unseed3,unseed4,unseed5,unseed10)
trtunseed <- trtunseed %>% add_column(add_column = "U")
trts <- bind_rows(trtseed,trtunseed)
 ### This is to add a seeding treatment to trts by way of using varibs in the chain ###
trts <- trts  %>% 
  filter(!is.na(row))

trts <- rename(trts, seed_trt = add_column)
trtsNP <- trts %>% left_join(dat1_summary_noPIPA, by= "plot_id") %>% column_to_rownames("plot_id")
# trtsNP is now the data frame to work off for models. It has biomass of all species except PIPA included
trts <- trts %>% left_join(dat1_summary, by = "plot_id")
glmtrts<- trts # this is trts before as I need to put into lme4
trts <- trts %>% column_to_rownames("plot_id")

trts$standbyrow <- paste(trts$stand, "_", trts$row)
trtsNP$standbyrow <- paste(trtsNP$stand, "_", trtsNP$row)
  ### This is to add a seeding treatment to trts by way of using varibs in the chain ###

trtsNP$binary<- with(trtsNP, ifelse(n_seedlings > 0, '1', '0')) %>% as.numeric()
trtsNP$stand <- as.factor(trtsNP$stand)
trtsNP$seed_trt <- as.factor(trtsNP$seed_trt)
trtsNP$row <- as.factor(trtsNP$row)





```


```{r "light testing between stands and treatments"}



seed1 <- data %>% filter(stand == 6)
seed2 <- data %>% filter(stand == 7)
seed3 <- data %>% filter(stand == 8)
seed4 <- data %>% filter(stand == 9)
trts5 <- bind_rows(seed1,seed2,seed3,seed4)
trts6 <- trts5 %>% add_column(add_column = "S") #all of this created new column with "S" for seeded

unse1 <- data %>% filter(stand == 3)
unse2 <- data %>% filter(stand == 4)
unse3 <- data %>% filter(stand == 5)
unse4 <- data %>% filter(stand == 10)
trtu5 <- bind_rows(unse1,unse2,unse3,unse4)
trtu5 <- trtu5 %>% add_column(add_column = "U") #all of this created new column with "U" for unseeded

data <- bind_rows(trts6, trtu5) #this mashed the two tables together (U) and (S)
data <- rename(data, seed_trt = add_column) #this changed the name of the new column to "seed_trt" which now contains a S or a U.
data$seed_trt <- as.factor(data$seed_trt)

meds <- aov(lai_2000_lin ~ row, data= data)
summary(meds)   #lai is significant by row !!!

beds <- aov(lai_2000_lin ~ stand, data= data)
summary(beds) #lai is significant by stand !!!

leads <- aov(lai_2000_lin ~ seed_trt, data= data)
summary(leads) #lai is significant by seed_trt !!!



lighttest <- data %>% summarise(plot_id, n_seedlings, openness, lai_2000_lin, ppfd_total_under_per_day_m_jor_mol_m2day, gap_fraction, row, stand, transect, seed_trt) %>% group_by(stand, row, seed_trt) %>% 
  summarise(ppfdaverage = mean(ppfd_total_under_per_day_m_jor_mol_m2day), 
            gap_fractionaverage=mean(gap_fraction),
            lai_2000_linaverage = mean(lai_2000_lin),
            opennessaverage = mean(openness))

test3 <- aov(gap_fractionaverage ~ seed_trt, data= lighttest)
summary(test3)

test4 <- aov(gap_fractionaverage ~ stand, data= lighttest)
summary(test4)

test5 <- aov(gap_fractionaverage ~ row, data= lighttest)
summary(test5)

range(data$gap_fraction)
mean(lighttest$gap_fractionaverage)
range(lighttest$gap_fractionaverage)

ggplot(data=lighttest, aes(x=seed_trt, y=gap_fractionaverage)) +
  geom_boxplot() +labs(y= "Mean Gap Fraction", x = "Seeding Treatment") +theme_minimal() 

ggplot(lighttest, aes(
  x = factor(stand, levels = c(3, 4, 5, 10, 6, 7, 8, 9)),
  y = gap_fractionaverage,
  fill = gap_fractionaverage
)) +   geom_boxplot() + theme_minimal()


letter_data <- data.frame(letters = c("a", "b"), seed_trt = c("S", "U"))

data_quantiles <- lighttest %>% 
  group_by(seed_trt) %>% 
  summarise(gap_quant = quantile(gap_fractionaverage)[4],
            lai_quant = quantile(lai_2000_linaverage)[4],
            canopy_quant = quantile(opennessaverage))

letter_data <- letter_data %>% left_join(data_quantiles)

ggplot(lighttest, aes(x = seed_trt, y = gap_fractionaverage)) +
       geom_boxplot() +
       theme_minimal() +
        geom_text(data = letter_data, aes(x = seed_trt, y = gap_quant, label = letters), size = 4, color = "black", hjust = -1.25, vjust = -0.8, fontface = "bold") +labs(y= "Mean Gap Fraction", x = "Seeding Treatment")








```

```{r "more light checking" }

light<- trtsNP %>% group_by(stand, row, seed_trt) %>% summarise(light_mean = mean(ppfd_total_under_per_day_m_jor_mol_m2day))


yes<-aov(light_mean ~ seed_trt, data= light)
summary(yes)
ao <- aov(trtsNP$ppfd_total_under_per_day_m_jor_mol_m2day ~ seed_trt, data= trtsNP)
summary(ao)


cor(data$openness, data$gap_fraction)
cor(trtsNP$n_seedlings,trtsNP$ppfd_total_under_per_day_m_jor_mol_m2day )
cor(trtsNP$biomass_sum,trtsNP$ppfd_total_under_per_day_m_jor_mol_m2day ) # corelation 0.2647


summary(lm(biomass_sum ~ seed_trt, data= trtsNP))

```


```{r}
library(glmmADMB)


#this is a model that josh sent me

fit_binary <- glmmadmb(binary ~ biomass_sum,
 random = ~1 | stand/row, family='binomial', link='cloglog',
 data=trtsNP)
summary(fit_binary) ### fit_binary has a significant factor of biomass_sum
ranef(fit_binary)


#this is a model that josh sent me

fit_binary2 <- glmmadmb(binary ~ seed_trt,
  random = ~1 | stand/row, family='binomial', link='cloglog',
  data=trtsNP)

summary(fit_binary2)



# this is another model from Josh
fit_hpoiss <- glmmadmb(n_seedlings ~ biomass_sum+ppfd_total_under_per_day_m_jor_mol_m2day+ seed_trt,
  random = ~1 | stand/row,
  data = subset(trtsNP, n_seedlings > 0),
  family = "truncpoiss")
 
summary(fit_hpoiss)


#This actually has a lower AIC##
fit_hpoiss2 <- glmmadmb(n_seedlings ~ biomass_sum*ppfd_total_under_per_day_m_jor_mol_m2day + seed_trt,
  random = ~1 | stand/row,
  data = subset(trtsNP, n_seedlings > 0),
  family = "truncpoiss")
 
summary(fit_hpoiss2)
plot(fit_hpoiss2$fitted)


```





```{r "This makes a AIC table and orders them based on the lowest AIC"}


finalmodlist <- list(fit_binary,fit_binary2, fit_hpoiss, fit_hpoiss2) # within the list() place the model call.names/ matrix names 
aictable<- data.frame("Model" = rep(" ",times=length(finalmodlist)),"AIC" = rep(NA,times=length(finalmodlist)))
for(i in 1:length(finalmodlist)){
  aictable$Model[i] <- as.character(finalmodlist[[i]]$formula)[3]
  aictable$AIC[[i]]<- summary(finalmodlist[[i]])$aic[1]
   aictable$nll[i] <- finalmodlist[[i]]$loglik
} #this created a shell and a loop (I don't fully comprehend loops)
orderedAICtablet <- aictable[order(aictable$AIC),] #this orders the aic table by AIC
orderedAICtablet$deltaAIC <- orderedAICtablet$AIC - orderedAICtablet$AIC[1] #this adds a delta AIC
orderedAICtablet$rll <- exp(-0.5*orderedAICtablet$deltaAIC) # this adds a rll value
orderedAICtablet$weight <- orderedAICtablet$rll/sum(orderedAICtablet$rll) #this adds weight
orderedAICtablet$weight <- round(orderedAICtablet$weight,3)  #this changes the weights to be rounded to 3 sig figs.
# write.csv(orderedAICtable_finalset, file = "AICtable_finalset.csv") #this writes the AIC Table into a CSV


```

### Close down all NMDS Stuff ###

```{r}

#check if there is a significant weight difference between row types




```



```{r "Vegitables", cache=TRUE}
#vegan analysis

nmdsE <- metaMDS(comm = input_dat,
             autotransform = FALSE,
             distance = "bray",
             engine = "monoMDS",
             k = 3,
             parallel = clus,
             weakties = TRUE,
             model = "global",
             maxit = 5000,
             try = 2000,
             trymax = 2000)
nmdsE
nmdsE$stress
plot(nmdsE)

ef <- envfit(nmdsE ~ lai_2000_lin, trts, permutations = 99999, choices = 1:2, na.rm=T, iterations = 1000)




ordiplot(nmdsE,type="n") #Ordination plot function especially for congested plots
orditorp(nmdsE,display="species",col="red",air=0.01) #The function adds text or points to ordination plots
orditorp(nmdsE,display="sites",cex=0.25,air=0.01)
ef

vegan3d::ordiplot3d(nmdsE, display="sites", choices = 1:3)
vegan3d::ordiplot3d(nmdsE, display="species",col="red", choices = 1:3)
```

```{r, cache=TRUE}

ef <- envfit(nmdsE ~ lai_2000_lin, trts, permutations = 99999, choices = 1:3, na.rm=T, iterations = 1000)
ef

ef1 <- envfit(nmdsE ~ stand, trts, permutations = 99999, choices = 1:3, na.rm = T, iterations= 1000)
ef1 #Significant ! ! !

ef2 <- envfit(nmdsE ~ n_seedlings, trts, permutations = 99999, choices = 1:3, na.rm = T, iterations= 1000)
ef2

ef3 <- envfit(nmdsE ~ seed_trt, trts, permutations = 99999, choices = 1:3, na.rm = T, iterations= 1000)
ef3 #Significant ! ! !
# how was this tested? what does this test do? look at : https://www.flutterbys.com.au/stats/tut/tut15.1.html

efstand <- envfit(nmdsE ~ stand, trts, permutations = 99999, choices = 1:3, na.rm = T, iterations= 1000)
efstand

ef4 <- envfit(nmdsE ~ ppfd_total_under_per_day_m_jor_mol_m2day, trts, permutations = 99999, choices = 1:3, na.rm = T, iterations= 1000)
ef4

ef5 <- envfit(nmdsE ~ openness, trts, permutations = 99999, choices = 1:3, na.rm = T, iterations= 1000)
ef5

ef6 <- envfit(nmdsE ~ gap_fraction, trts, permutations = 99999, choices = 1:3, na.rm = T, iterations= 1000)
ef6

ef7 <- envfit(nmdsE ~ biomass_sum, trts, permutations = 99999, choices = 1:3, na.rm = T, iterations= 1000)
ef7

ef8 <- envfit(nmdsE ~ row, trts, permutations = 99999, choices = 1:3, na.rm = T, iterations= 1000)
ef8

f <-tibble(ef$vectors$arrows[1:3]) %>% rename(lai_2000_lin= "ef$vectors$arrows[1:3]")
f1<-tibble(ef1$vectors$arrows[1:3]) %>% rename(stand= "ef1$vectors$arrows[1:3]")
f2<-tibble(ef2$vectors$arrows[1:3]) %>% rename(n_seedlings= "ef2$vectors$arrows[1:3]")
#f3<-tibble(ef3$vectors$arrows[1:3]) %>% rename(seed_trt= "ef3$vectors$arrows[1:3]")
f4<-tibble(ef4$vectors$arrows[1:3]) %>% 
  rename(ppfd_total_under_per_day_m_jor_mol_m2day= "ef4$vectors$arrows[1:3]")
f5<-tibble(ef5$vectors$arrows[1:3]) %>% rename(openness= "ef5$vectors$arrows[1:3]")
f6<-tibble(ef6$vectors$arrows[1:3]) %>% rename(gap_fraction= "ef6$vectors$arrows[1:3]")
f7<-tibble(ef7$vectors$arrows[1:3]) %>% rename(biomass_sum= "ef7$vectors$arrows[1:3]")
#f8<-tibble(ef8[["factors"]][["centroids"]]) %>% rename(row= ef8[["factors"]][["centroids"]])


flist <- bind_cols(f,f1,f2,f4,f5,f6,f7) %>% as.data.frame()
   rownames(flist) = c("NMDS1", 
                                 "NMDS2",
                                "NMDS3")
flist

rank_flist<-abs(flist)
max(rank_flist[1,]) # Stand is most highly corelated with NMDS1
max(rank_flist[2,]) # n_seedlings is most highly corelated with NMDS2
max(rank_flist[3,]) # biomass_sum is most highly corelated with NMDS3


write.csv(flist, "C:/Users/gn238/Downloads/vector_associations.csv", row.names=T)

```
```{r "why we use k=3", cache=TRUE}

ef_flat<-envfit(nmdsE ~ lai_2000_lin, trts, permutations = 99999, choices = 1:2, na.rm=T, iterations = 1000)
ef_flat

summary(ef_flat)
summary(ef2)

nmdsE

n = 10
stress <- vector(length = n)
for (i in 1:n) {
    stress[i] <- metaMDS(input_dat, distance = "bray", k = i)$stress
}
names(stress) <- paste0(1:n, "Dim")
# x11(width = 10/2.54, height = 7/2.54)
par(mar = c(3.5,3.5,1,1), mgp = c(2, 0.6, 0), cex = 0.8, las = 2)
barplot(stress, ylab = "stress")

```


```{r}
#plot some CCAs or RDAs

ord<- cca(input_dat ~ n_seedlings + biomass_sum + stand, data=trtsNP) #this creates cca with the constraints on n_seedlings, biomass sum and stand.
ord

plot(ord)
anova.cca(ord)
anova(ord, by="term", permutations = 199) # one way to run the cca anova
anova(ord, by="axis", permutations = 199) # the other way to run the cca anova

ord2<- cca(input_dat ~ biomass_sum + stand + trtsNP$transect, data=trtsNP)
ord2

anova.cca(ord2)
anova(ord2, by = "term", permutations = 199) #checking if a different CCA gives different results



```
```{r}

 
 #lets make a biomass difference table to see if there is a sig diff in biomass between stands/rows
 
 BIOMASS_TRANSECT_SUMMARY   <- trts %>% group_by(stand, row, transect, seed_trt) %>% 
            summarise(biomass_sum_row = mean(biomass_sum),
            biomass_sum_sd = sd(biomass_sum))
 
 head(BIOMASS_TRANSECT_SUMMARY,16)
bio<- lm(biomass_sum_row ~ seed_trt, data=BIOMASS_TRANSECT_SUMMARY)
summary(bio) #0.00133 **        !!!!!

Test1<- lm(biomass_sum_row ~ row, data=BIOMASS_TRANSECT_SUMMARY)
summary(Test1) #row is not significant for the biomass differentals 


 #seed treatment had a pvalue of 0.00133 for effecting biomass differentials between treatments WHEN MEASURING DOWN TO THE TRANSECT (REPLICATE IS TRANSECTS WITHIN THE STAND)
 
 BIOMASS_ROW_SUMMARY   <- trts %>% group_by(stand, row, seed_trt) %>% 
            summarise(biomass_sum_row = mean(biomass_sum),
            biomass_sum_sd = sd(biomass_sum))
 
 head(BIOMASS_ROW_SUMMARY,16)
bio2<- lm(biomass_sum_row ~ seed_trt, data=BIOMASS_ROW_SUMMARY)
summary(bio2) #0.057
#seed treatment had a pvalue of 0.057 for effecting biomass differentials between treatments WHEN MEASURING BASED ON ROW AVERAGES PER STAND (REPLICATE IS ROW TYPE IN EACH STAND)
 Test2<- lm(biomass_sum_row ~ row, data=BIOMASS_ROW_SUMMARY)
summary(Test2) #row is not significant for the biomass differentals 


seedday <- BIOMASS_ROW_SUMMARY %>% filter(seed_trt == "S")
mean(seedday$biomass_sum_row) # 199.5352
mean(seedday$biomass_sum_sd) # 93.69091

unseedday <- BIOMASS_ROW_SUMMARY %>% filter(seed_trt == "U")
mean(unseedday$biomass_sum_row) # 145.2537
mean(unseedday$biomass_sum_sd) # 75.65474

```


```{r}

dat1_summary  #this is the biomass table for all spp

dat1_summary_noPIPA # this is the biomass table for all spp !PIPA


#this is a df with species weight on the inside and plot & species as headers
input_dat <- dat1 %>% column_to_rownames("plot_id")
#this is a df with species weight on the inside and plot & species as headers



  #plot side/axis 1 and 2 of 3D figure
  
  ### This is to add a seeding treatment to trts by way of using varibs in the chain ###

seeded6 <- varibs %>% filter(stand == 6)
seeded7 <- varibs %>% filter(stand == 7)
seeded8 <- varibs %>% filter(stand == 8)
seeded9 <- varibs %>% filter(stand == 9)
trtseed <- bind_rows(seeded6,seeded7,seeded8,seeded9)
trtseed <- trtseed %>% add_column(add_column = "S")

unseed3 <- varibs %>% filter(stand == 3)
unseed4 <- varibs %>% filter(stand == 4)
unseed5 <- varibs %>% filter(stand == 5)
unseed10 <- varibs %>% filter(stand == 10)
trtunseed <- bind_rows(unseed3,unseed4,unseed5,unseed10)
trtunseed <- trtunseed %>% add_column(add_column = "U")

trts <- bind_rows(trtseed,trtunseed) # attached the two treatments and rejoined the whole data group with the new rows, S and U
### This is to add a seeding treatment to trts by way of using varibs in the chain ###
trts <- trts  %>% 
  filter(!is.na(row))

trts <- rename(trts, seed_trt = add_column) # this changed the name of the new column I just made to be seed_trt from add_column.

trtsNP <- trts %>% left_join(dat1_summary_noPIPA, by= "plot_id") %>% column_to_rownames("plot_id")
# trtsNP is now the data frame to work off for models. It has biomass of all species except PIPA included
trts <- trts %>% left_join(dat1_summary, by = "plot_id")
trts <- trts %>% column_to_rownames("plot_id")

trts$standbyrow <- paste(trts$stand, "_", trts$row)
trtsNP$standbyrow <- paste(trtsNP$stand, "_", trtsNP$row)
  ### This is to add a seeding treatment to trts by way of using varibs in the chain ###

trtsNP$binary<- with(trtsNP, ifelse(n_seedlings > 0, '1', '0')) %>% as.numeric() #this added a bionary row that is based on if there was any regen. if yes, there is a 1 populated, if no regen quantiites, then a 0 is populated.
trtsNP$stand <- as.factor(trtsNP$stand)
trtsNP$seed_trt <- as.factor(trtsNP$seed_trt)
trtsNP$row <- as.factor(trtsNP$row)



```

```{r "Try to see if lme4 can solve the transect problem"}
#this entire chunk was just to see if I could tease out if transects were more important for finding seedlings than row type. I came up empty handed so I am basing my new tests off of row types because transects are less representitive and would be harder to defend.

library(lme4)
library(lmerTest)


head(glmtrts)
glmtrts<- glmtrts %>% separate(col = plot_id,  into = c("stand", "transect", "position")) #this gives a new column for each by separating stand, transect, and position
glmtrts$trans_po <- paste(glmtrts$stand, "_", glmtrts$plot_id)
glmtrts$binary<- with(glmtrts, ifelse(n_seedlings > 0, '1', '0')) %>% as.numeric()
#glmtrts$plot_id<- as.factor(glmtrts$plot_id)
glmtrts$stand <- as.factor(glmtrts$stand)
glmtrts$transect <- as.factor(glmtrts$transect)
glmtrts$seed_trt <- as.factor(glmtrts$seed_trt)
glmtrts$row <- as.factor(glmtrts$row)
glmtrts$position <- as.factor(glmtrts$position)
glmtrts$trans_po <- as.factor(glmtrts$trans_po)

#trans_po (subset of plot Id?)



m1<-glmer(biomass_sum ~ seed_trt + (1| stand/transect),
               data = glmtrts)
summary(m1) # this is biomass sum being predicted by seed treatments with the random effects of nesting transect within row within stand.

# this is a nested random effect in lme4 <- (1|group1/group2)
#where group2 is nested within group1.

#this is a crossed random effect (not nested) <- (1|group1) + (1|group2)
#where group1 has crossed random effects with group2

hey <- lm(data=glmtrts, n_seedlings ~ seed_trt)
summary(hey) # a glm model that predicts seedling based on if there was a seed trt or not. SIG


```
```{r}
library(vegan)
trts$stand <- as.factor(trts$stand) # set stand as a factor within trts
trts$seed_trt <- as.factor(trts$seed_trt) # set seed_trt as a factor within trts

adonis2(input_dat ~ seed_trt/stand, ##seed_treet nested in stand is very significant for spp composition differences
        trts,
        permutations = 99999,
        method= "bray",
        sqrt.dist = F,
        by= "terms" #,
        #parallel = clus #,  # if there is an error in Serialize, then remove running using a cluster
       #strata = trts$seed_trt
      )

 adonis2(input_dat ~ stand, #stand is very significant for spp composition differences
        trts,
        permutations = 99999,
        method= "bray",
        sqrt.dist = F,
        by= "terms" #,
       # parallel = clus
      )

  adonis2(input_dat ~ stand:seed_trt, #This is SIG 0.00508 and means that stand is nested within seed treatment
        trts,
        permutations = 99999,
        method= "bray",
        sqrt.dist = F,
        by= "terms" #,
       # parallel = clus
      )
 
adonis2(input_dat ~ seed_trt + stand + row, #seed trt alone is .06188
        trts,
        permutations = 99999,
        method= "bray",
        sqrt.dist = F,
        by= "terms",
        parallel = clus #,
         # strata = trts$stand
      )

adonis2(input_dat ~ row, # row is not significant
        trts,
        permutations = 99999,
        method= "bray",
        sqrt.dist = F,
        by= "terms",
        parallel = clus #,
       # strata= trts$row
      )

adonis2(input_dat ~ ppfd_total_under_per_day_m_jor_mol_m2day, # light is def not sig.
        trts,
        permutations = 99999,
        method= "bray",
        sqrt.dist = F,
        by= "terms",
        parallel = clus
      )

adonis2(input_dat ~ n_seedlings, # n_seedlings is def not sig.
        trts,
        permutations = 99999,
        method= "bray",
        sqrt.dist = F,
        by= "terms",
        parallel = clus
      )


```
```{r}
this <- read_csv("C:/Users/gn238/Downloads/gn_metadata_wzeros.csv")
this <- this %>% mutate(species_code = coalesce(species_code,species))
this <- this %>% filter(!plot_id=="9-6-K")
this <- this %>% filter(!is.na(species_code))
#get rid of the entries without a species code after the coalesce.

permA_input_dat <- this%>% dplyr::select(plot_id, row, species_code, dried_weight_g) %>%
  pivot_wider(names_from = species_code, values_from = dried_weight_g, values_fn = sum, values_fill = 0)
permA_input_dat %>% dplyr::mutate(row= replace_na("L"))

#These are for #input_dats per row type
permA_input_TO <- permA_input_dat %>% filter(row== "TO") %>% dplyr::select(-c(row)) %>% column_to_rownames("plot_id") 
permA_input_L <- permA_input_dat %>% filter(row== "L") %>% dplyr::select(-c(row)) %>% column_to_rownames("plot_id") 

#make some fun new df's #This is for TRTS
input_trts_row_TO <- trts %>% filter(row == "TO") #%>% column_to_rownames("plot_id") 
input_trts_row_L <- trts %>% filter(row == "L") %>% rownames_to_column() %>% filter(!rowname=="7-10-E") %>% column_to_rownames("rowname") 






adonis2(permA_input_TO~ seed_trt,
        input_trts_row_TO,
        permutations = 99999,
        method= "bray",
        sqrt.dist = F,
        by= "terms",
        parallel = clus
        ) #significant species composition change in the TAKE OUT rows ! ! !



#compare what values are in check and not chuck
#check <- permA_input_L %>% rownames_to_column()
#chuck <- input_trts_row_L %>% rownames_to_column()

#view(chuck %>%  #For df1 values not in df2 
#  filter(!chuck$rowname %in% check$rowname))
# so I need to get rid of 7-10-E from trts

#input_trts_row_L <- input_trts_row_L %>% filter(!rowname=="7-10-E") %>% column_to_rownames("rowname") 




adonis2(permA_input_L ~ seed_trt,
        input_trts_row_L,
        permutations = 99999,
        method= "bray",
        sqrt.dist = F,
        by= "terms",
        parallel = clus
        ) # NOT significant species composition change in the LEAVE rows ! ! !

#take away: you have to separate the two row types to get significant variation between the treatment via permanovas


```


```{r}

 # Use this link for help:
 # https://stackoverflow.com/questions/14711470/plotting-envfit-vectors-vegan-package-in-ggplot2

library(vegan)
library(ggplot2)
library(grid)
library(cowplot)
data(dune)

# calculate distance for NMDS

NMDS.log<-log1p(input_dat)

set.seed(42)

sol <- nmdsE

scrs <- as.data.frame(scores(sol, display = "species"))


set.seed(123)
vf <- envfit(sol, input_dat, choices= 1:2, perm = 999) #if you put NMDS.log instead of input dat, you get more spp.
vf3 <- envfit(sol, input_dat, choices= 1:3, perm = 999) #if you put NMDS.log instead of input dat, you get more spp.
vf
vf3 #3d

# I found that N_seedlings and PIPA dont point in the smame direction

spp.scrs <- as.data.frame(scores(vf, display = "vectors")) #2d
spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs))  #2d

arrow_factor <- ordiArrowMul(vf)
spp.scrs <- as.data.frame(scores(vf, display = "vectors")) * arrow_factor
spp.scrs <- cbind(spp.scrs, Species = rownames(spp.scrs), Pvalues = vf$vectors$pvals, R_squared = vf$vectors$r)
### two dimentions above
 

## three dimentions below ##
spp.scrs3 <- as.data.frame(scores(vf3, display = "vectors")) #3d
spp.scrs3 <- cbind(spp.scrs3, Species = rownames(spp.scrs3))  #3d

arrow_factor3 <- ordiArrowMul(vf3) #3d 
spp.scrs3 <- as.data.frame(scores(vf3, display = "vectors")) * arrow_factor3 #3d
spp.scrs3 <- cbind(spp.scrs3, Species = rownames(spp.scrs3), Pvalues = vf3$vectors$pvals, R_squared = vf3$vectors$r) # 3d
## three dimentions above ##


ef2.scrs <-as.data.frame(scores(ef2, display = "vectors")) #try to get ef2 into the ggplot (3d)
ef2.scrs <- cbind(ef2.scrs, Species = rownames(ef2.scrs))  #3d



# select significance similarly to `plot(vf, p.max = 0.01)`
spp.scrs
spp.scrs017 <- subset(spp.scrs, Pvalues < 0.017)
spp.scrs05  <- subset(spp.scrs, Pvalues < 0.05)
spp.scrs.rownames <- spp.scrs %>% rownames_to_column() 

spp.scrs3 #3d
spp.scrs3.05 <- subset(spp.scrs3, Pvalues < 0.05) #3d
#spp.scrs05  <- subset(spp.scrs, Pvalues < 0.05)
#spp.scrs.rownames <- spp.scrs %>% rownames_to_column() 



s1 <- filter(spp.scrs.rownames, rowname == 'SOAR') # these go and pull out the info for the selected spp
s2 <- filter(spp.scrs.rownames, rowname == 'TEVI')
s3 <- filter(spp.scrs.rownames, rowname == 'RUCU')
s4 <- filter(spp.scrs.rownames, rowname == 'CHNC')
s5 <- filter(spp.scrs.rownames, rowname == 'AN01')
s6 <- filter(spp.scrs.rownames, rowname == 'DEVI')
s7 <- filter(spp.scrs.rownames, rowname == 'PPG1')
s8 <- filter(spp.scrs.rownames, rowname == 'SONU')
interest <- s1 %>% bind_rows(s2) %>% bind_rows(s3) %>% bind_rows(s4) %>% bind_rows(s5) %>% bind_rows(s6) %>% bind_rows(s7) %>% bind_rows(s8) %>%
  column_to_rownames( var = "rowname")
# ef1 and ef4

n1 <- filter(spp.scrs3.05, Species == "PIPA")
n2 <- filter(spp.scrs3.05, Species == "PPG1")
n3 <- filter(spp.scrs3.05, Species == "SONU")
n4 <- filter(spp.scrs3.05, Species == 'CHNC')
n5 <- filter(spp.scrs3.05, Species == 'SOAR')
n6 <- filter(spp.scrs3.05, Species == 'DEST')
n7 <- filter(spp.scrs3.05, Species == 'WAMA')
n8 <- filter(spp.scrs3.05, Species == 'TEVI') #not as sig as others above
n9 <- filter(spp.scrs3.05, Species == "RUCU")
n10 <- filter(spp.scrs3.05, Species == "AN01")
n11 <- filter(spp.scrs3.05, Species == "ACGR")
interesting <- n1 %>% bind_rows(n2) %>% bind_rows(n3) %>% bind_rows(n4) %>% bind_rows(n5) %>% bind_rows(n6) %>% bind_rows(n7) %>% bind_rows(n8) 


finalspp <- n3 %>% bind_rows(n4) %>% bind_rows(n5) %>% bind_rows(n6) %>% bind_rows(n8) %>% bind_rows(n9) %>% bind_rows(n2) %>% bind_rows(n10) 


arrow_factor_ef1 <- ordiArrowMul(ef1) #this creates a distance for the arrow (ef1 is stand)
ef1.scrs <- as.data.frame(scores(ef1, display = "vectors")) * arrow_factor_ef1  #this creates the df for the arrow based on the NMDS and is linked to the centroid

#arrow_factor_ef3 <- ordiArrowMul(ef3) #this creates a distance for the arrow (ef3 is seed trt)
#f3.scrs <- as.data.frame(scores(ef3, display = "vectors")) * arrow_factor_ef3  #this creates the df for the arrow based on the NMDS and is linked to the centroid



#okay seed trt is complex. I am going to have to pull out individual vectors of seeded and unseeded
#cant seem to plot seed treatments individually.


p <- ggplot(scrs) +
  geom_point(mapping = aes(x = NMDS1, y = NMDS2)) +
  coord_fixed() + ## need aspect ratio of 1!
  geom_segment(data = interest, # data = whatever vectors you want
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "darkred") + #this is spp vector names
  geom_segment(data= ef1.scrs,aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
               arrow = arrow(length = unit(0.25, "cm")), colour = "orange1") + #this is the stand vector
    #geom_segment(data= ef3.scrs,aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
     #          arrow = arrow(length = unit(0.25, "cm")), colour = "red1") + #this is for ppfd_...
  geom_text(data = interest, aes(x = NMDS1, y = NMDS2, label = Species), # data = vector names 
            size = 4, color= "darkred") + theme_minimal() 
  #geom_text(data = ef1.scrs, aes(x = NMDS1, y = NMDS2, label = "stand", nudge_y = .25), # data = vector names 
   #         size = 5, color= "orange") + theme_minimal()

plot(p)




#the following is for picking what NMDS axis you want to represent!

p12 <- ggplot(scrs) +
  geom_point(mapping = aes(x = NMDS1, y = NMDS2)) + # HERE YOU CAN CHANGE THE AXIS 
  coord_fixed() + ## need aspect ratio of 1!
  geom_segment(data = interesting, # data = whatever vectors you want
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2), # HERE YOU CAN CHANGE THE AXIS 
               arrow = arrow(length = unit(0.25, "cm")), colour = "darkred") + #this is spp vector names
  #geom_segment(data= ef1.scrs,aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
    #           arrow = arrow(length = unit(0.25, "cm")), colour = "orange1") + #this is the stand vector
    #geom_segment(data= ef3.scrs,aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
     #          arrow = arrow(length = unit(0.25, "cm")), colour = "red1") + #this is for ppfd_...
  geom_text(data = interesting, aes(x = NMDS1, y = NMDS2, label = Species), # data = vector names    # HERE YOU CAN CHANGE THE AXIS 
            size = 4, color= "darkred") + theme_minimal() 
  #geom_text(data = ef1.scrs, aes(x = NMDS1, y = NMDS2, label = "stand", nudge_y = .25), # data = vector names 
   #         size = 5, color= "orange") + theme_minimal()

plot(p12)




p23 <- ggplot(scrs) +
  geom_point(mapping = aes(x = NMDS2, y = NMDS3)) + # HERE YOU CAN CHANGE THE AXIS 
  coord_fixed() + ## need aspect ratio of 1!
  geom_segment(data = interesting, # data = whatever vectors you want
               aes(x = 0, xend = NMDS2, y = 0, yend = NMDS3), # HERE YOU CAN CHANGE THE AXIS 
               arrow = arrow(length = unit(0.25, "cm")), colour = "darkred") + #this is spp vector names
  #geom_segment(data= ef1.scrs,aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
    #           arrow = arrow(length = unit(0.25, "cm")), colour = "orange1") + #this is the stand vector
    #geom_segment(data= ef3.scrs,aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
     #          arrow = arrow(length = unit(0.25, "cm")), colour = "red1") + #this is for ppfd_...
  geom_text(data = interesting, aes(x = NMDS2, y = NMDS3, label = Species), # data = vector names    # HERE YOU CAN CHANGE THE AXIS 
            size = 4, color= "darkred") + theme_minimal() 
  #geom_text(data = ef1.scrs, aes(x = NMDS1, y = NMDS2, label = "stand", nudge_y = .25), # data = vector names 
   #         size = 5, color= "orange") + theme_minimal()

plot(p23)



p77 <- ggplot(scrs) +
  geom_point(mapping = aes(x = NMDS2, y = NMDS3)) + # HERE YOU CAN CHANGE THE AXIS 
  coord_fixed() + ## need aspect ratio of 1!
  geom_segment(data = finalspp, # data = whatever vectors you want
               aes(x = 0, xend = NMDS2, y = 0, yend = NMDS3), # HERE YOU CAN CHANGE THE AXIS 
               arrow = arrow(length = unit(0.25, "cm")), colour = "darkred") + #this is spp vector names
  #geom_segment(data= ef1.scrs,aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
    #           arrow = arrow(length = unit(0.25, "cm")), colour = "orange1") + #this is the stand vector
    #geom_segment(data= ef3.scrs,aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
     #          arrow = arrow(length = unit(0.25, "cm")), colour = "red1") + #this is for ppfd_...
  ggrepel::geom_text_repel(data = finalspp, aes(x = NMDS2, y = NMDS3, label = Species), cex = 3, direction = "both", # data = vector names    # HERE YOU CAN CHANGE THE AXIS 
            size = 7, color= "darkred") + theme_minimal() 
  #geom_text(data = ef1.scrs, aes(x = NMDS1, y = NMDS2, label = "stand", nudge_y = .25), # data = vector names 
   #         size = 5, color= "orange") + theme_minimal()

plot(p77) # this has been placed in the thesis


p78 <- ggplot(scrs) +
  geom_point(mapping = aes(x = NMDS1, y = NMDS3)) + # HERE YOU CAN CHANGE THE AXIS 
  coord_fixed() + ## need aspect ratio of 1!
  geom_segment(data = finalspp, # data = whatever vectors you want
               aes(x = 0, xend = NMDS1, y = 0, yend = NMDS3), # HERE YOU CAN CHANGE THE AXIS 
               arrow = arrow(length = unit(0.25, "cm")), colour = "darkred") + #this is spp vector names
  #geom_segment(data= ef1.scrs,aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
    #           arrow = arrow(length = unit(0.25, "cm")), colour = "orange1") + #this is the stand vector
    #geom_segment(data= ef3.scrs,aes(x = 0, xend = NMDS1, y = 0, yend = NMDS2),
     #          arrow = arrow(length = unit(0.25, "cm")), colour = "red1") + #this is for ppfd_...
  ggrepel::geom_text_repel(data = finalspp, aes(x=NMDS1, y=NMDS3, label = Species), cex = 3, direction = "both", 
 # geom_text(data = finalspp, aes(x = NMDS1, y = NMDS3, label = Species), # data = vector names    # HERE YOU CAN CHANGE THE AXIS 
            size= 7, color= "darkred") + theme_minimal() 
  #geom_text(data = ef1.scrs, aes(x = NMDS1, y = NMDS2, label = "stand", nudge_y = .25), # data = vector names 
   #         size = 5, color= "orange") + theme_minimal()

plot(p78) # this has been placed in the thesis

plot_grid(p77, p78, labels = c('(A)', '(B)'), label_size = 12)

```

```{r "Axis corelation vectors on the original [base R] plot types"}
#lets force this code.

ef_seedlings <- envfit(nmdsE ~ n_seedlings, trts, permutations = 99999, choices = 2:3, na.rm = T, iterations= 1000)
ef_seedlings #this is for the second plot only (only has axis 2 and 3 of nmds)


efstand <- envfit(nmdsE ~ stand, trts, permutations = 99999, choices = 2:3, na.rm = T, iterations= 1000)
efstand #this is for the second plot only (only has axis 2 and 3 of nmds)



ef_biomass <- envfit(nmdsE ~ biomass_sum, trts, permutations = 99999, choices = 2:3, na.rm = T, iterations= 1000)
ef_biomass #this is for the second plot only (only has axis 2 and 3 of nmds)

ef_lai <- envfit(nmdsE ~ lai_2000_lin, trts, permutations = 99999, choices = 2:3, na.rm=T, iterations = 1000)
ef_lai



# option 1 (I dont like it) 
#visual number 3
ordiplot(nmdsE,type="n") #Ordination plot function especially for congested plots
orditorp(nmdsE,display="sites",col="red",air=0.01) #The function adds text or points to ordination plots
plot(ef1) + plot(ef2) 

#visual number 2
ordiplot(nmdsE,type="n", choices = 2:3) #Ordination plot function especially for congested plots
orditorp(nmdsE,display="sites",col="red",air=0.01, choices = 2:3) #The function adds text or points to ordination plots
plot(ef_biomass) + plot(ef_seedlings) 






C:/Users/gn238/Downloads/gn_metadata_wzeros.csv




# Step 2: Create the plot with R code
plot(nmdsE, display="sites" , xlim = c(-2,2)) #,  ylim = c(-1.25,1.25)) 
points(nmdsE, display = "sites", pch = 16, col = "black")
plot(ef1, col= "maroon") + plot(ef2, col= "maroon") +plot(ef, col= "maroon")

# Step 3: Run dev.off() to create the file!

plot(nmdsE, display = "sites",  choices = 2:3)
points(nmdsE, display = "sites", pch = 16, col = "black", choices= 2:3)
plot(ef_biomass, col= "maroon") + plot(ef_lai, col= "maroon") +
plot(ef_seedlings, arrow.mul = 10, col= "maroon")

# now square


plot(nmdsE$points, display="sites" , xlim = c(-2,2)) 
points(nmdsE, display = "sites", pch = 16, col = "black")
plot(ef1, col= "maroon") + plot(ef2, col= "maroon") +plot(ef, col= "maroon")

# Step 3: Run dev.off() to create the file!

plot(nmdsE, display = "sites",  choices = 2:3)
points(nmdsE, display = "sites", pch = 16, col = "black", choices= 2:3)
plot(ef_biomass, col= "maroon") + plot(ef_lai, col= "maroon") +
plot(ef_seedlings, arrow.mul = 10, col= "maroon")


```



```{r "more immages for the pub"}
#HERE I WILL BE WORKING TO CREATE A SPECIES GRAPH PER STAND
sp<- c("MUEX","SONU","SOSE","TEVI","ARBE", "PAVI")

SONU_plots <- data %>% summarise(stand, row, species_code, dried_weight_g, seed_trt) %>%
                      group_by(seed_trt, stand,row,species_code)  %>%
                      summarise(spp_biomass =sum(dried_weight_g)) %>%
                      group_by(seed_trt, stand, row, species_code) %>% summarise(spp_biomass = sum(spp_biomass)) %>%
                      filter(species_code == "SONU")
SOSE_plots <- data %>% summarise(stand, row, species_code, dried_weight_g, seed_trt) %>%
                      group_by(seed_trt, stand,row,species_code)  %>%
                      summarise(spp_biomass =sum(dried_weight_g)) %>%
                      group_by(seed_trt, stand, row, species_code) %>% summarise(spp_biomass = sum(spp_biomass)) %>%
                      filter(species_code == "SOSE")
TEVI_plots <- data %>% summarise(stand, row, species_code, dried_weight_g, seed_trt) %>%
                      group_by(seed_trt, stand,row,species_code)  %>%
                      summarise(spp_biomass =sum(dried_weight_g)) %>%
                      group_by(seed_trt, stand, row, species_code) %>% summarise(spp_biomass = sum(spp_biomass)) %>%
                      filter(species_code == "TEVI")
ARBE_plots <- data %>% summarise(stand, row, species_code, dried_weight_g, seed_trt) %>%
                      group_by(seed_trt, stand,row,species_code)  %>%
                      summarise(spp_biomass =sum(dried_weight_g)) %>%
                      group_by(seed_trt, stand, row, species_code) %>% summarise(spp_biomass = sum(spp_biomass)) %>%
                      filter(species_code == "ARBE")
MUEX_plots <- data %>% summarise(stand, row, species_code, dried_weight_g, seed_trt) %>%
                      group_by(seed_trt, stand,row,species_code)  %>%
                      summarise(spp_biomass =sum(dried_weight_g)) %>%
                      group_by(seed_trt, stand, row, species_code) %>% summarise(spp_biomass = sum(spp_biomass)) %>%
                      filter(species_code == "MUEX")
PAVI_plots <- data %>% summarise(stand, row, species_code, dried_weight_g, seed_trt) %>%
                      group_by(seed_trt, stand,row,species_code)  %>%
                      summarise(spp_biomass =sum(dried_weight_g)) %>%
                      group_by(seed_trt, stand, row, species_code) %>% summarise(spp_biomass = sum(spp_biomass)) %>%
                      filter(species_code == "PAVI")
spp_plots <- bind_rows(ARBE_plots,TEVI_plots,SOSE_plots,SONU_plots,PAVI_plots)


df123 <- data.frame( stand = c(3,3), #here I am createing an empty table for stand 3 so that I can merge it into the other table to get zero values in the ggplot below
seed_trt = c("U","U"),                     
row = c("TO", "L"),
species_code = c("ARBE", "ARBE"),
spp_biomass = c(0,0))
spp_plots <- bind_rows(spp_plots, df123)



spp_plots['seed_trt'][spp_plots['seed_trt'] == "S"]<- "Seeded"
spp_plots['seed_trt'][spp_plots['seed_trt'] == "U"]<- "Unseeded"
# create a dataset
# stand <- c(rep("sorgho" , 3) , rep("poacee" , 3) , rep("banana" , 3) , rep("triticum" , 3) ) #specie in example
# species <- rep(c("normal" , "stress" , "Nitrogen") , 4) #condition in example
# biomass <- abs(rnorm(12 , 0 , 15)) #value in example
# spp_plots <- data.frame(specie,condition,value)


     #  wt_bar <- (ggplot(spp_plots, aes(fill=species_code,  y=spp_biomass,  x = factor(stand, levels = c(3, 4, 5, 10, 6, 7, 8, 9))))
# Stacked




wt_bar <- (ggplot(spp_plots, aes(fill=species_code,  y=spp_biomass,  x = factor(stand, levels = c(3, 4, 5, 10, 6, 7, 8, 9)))) + 
    geom_bar(position="stack", stat="identity") +
         scale_x_discrete("stand", drop = T) +
            scale_fill_manual("legend", values = c("ARBE" = "red3", "SONU" = "orange2", 
                                                   "SOSE" = "turquoise", "TEVI"= "blue2", 
                                                   "PAVI" = "green2"))+
               labs(y="Species Biomass(g)") +
               theme_minimal())
  
wt_bar + facet_grid(cols = vars(seed_trt),drop=F, scales = "free_x")








spp_plots$standbyrow <- paste(spp_plots$stand, "_", spp_plots$row) #this created a new row in spp_plots for "stand_by_row" a mixture of how does row type and stand interact 
spp_plots$standbyrow <- as.factor(spp_plots$standbyrow) #turns standbyrow into a factor

spp_plots <- spp_plots %>% filter(!is.na(row)) #this gets rid of the empty row value in stand 7. it subtracted .17 grams of a sppecies, but it was already recorded in that stand so I think obmiting it is alright in this visual
LEVELS <- c('3_L',"3_TO", "4_L","4_TO", "5_L", "5_TO", "10_L","10_TO", "6_L", "6_TO", "7_L", "7_TO", "8_L", "8_TO", "9_L", "9_TO")

ggplot(spp_plots, aes(fill=species_code,  y=spp_biomass,  x = factor(standbyrow))) + 
    geom_bar(position="stack", stat="identity") +
         scale_x_discrete("standbyrow", drop = FALSE) +
            scale_fill_manual("legend", values = c("ARBE" = "red3", "SONU" = "orange2", 
                                                   "SOSE" = "turquoise", "TEVI"= "blue2"))+
               labs(y="Species Biomass(g)", x= " Stand ") + theme_minimal()


```


```{r "see what most and least likely spp are for each trt"}

review_seeded<- data %>% summarise(seed_trt, species_code, species) %>% filter(seed_trt == "S") %>%
  count(species_code, name="spp_count", sort = TRUE)  %>% 
  slice_max(n=114, order_by = spp_count, with_ties = FALSE)
  
  
  review_unseeded<- data %>% summarise(seed_trt, species_code, species) %>% filter(seed_trt == "U") %>%
  count(species_code, name="spp_count", sort = TRUE)  %>% 
  slice_max(n=114, order_by = spp_count, with_ties = FALSE)



  table_for_appendix<- data %>% summarise(species_code, species) %>% unique()
  
    table_for_appendix<- data %>% dplyr::select( species_code) %>% unique()
  
  
  table_for_appendix<- table_for_appendix %>% left_join(data, by = "species_code") %>% summarize(species_code, species) %>% unique() %>% filter(!species = ("Unk"))

```

```{r}

```



